services:
  db:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "flask-crud"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3361:3306"
    expose:
      # Opens port 3306 on the container
      - "3361"
    volumes:
      - ./mysql:/var/lib/mysql
